hass/configurations.js, hass/devices.js
The device payload or lights has been changed and should work for all zwave lights. Lights now will turn on to their previous state if a brightness is not specified.
The fan payload for the GE/Jasco fans is now fixed so that the fan does not always turn on "high" by default. It will turn on to its previous state by default.
=> Fixes for lights, fans, and contact sensors in home assistant

hass/devices.js
Fans were not setting their speed correctly anymore. This PR fixes that issue.
=> [fix] GE fan speeds not reporting correctly

lib/Gateway.js
Currently, it is not possible to disable node polling once that it has been enabled. This PR fixes that.
=> [fix] Disable z-wave node polling if polling is not set in settings

hass/devices.js
Added Home Assistant support for [Eurotronic Spirit Z-Wave Plus](https://eurotronic.org/produkte/z-wave-heizkoerperthermostat/spirit-z-wave-plus/) thermostat via custom component.
=> Add Eurotronic Sprit Z-Wave Plus as custom component

hass/configurations.js
The command_on_template should return a value between 0 and 99
=> Fix command_on_template for light_dimmer

hass/configurations.js
This reverts the code in #125 so that dimmers can turn on to their previous brightness.
=> Dimmers turn on to previous brightness by default

lib/Gateway.js
Currently I have several rebranded Danfoss LC13's.
These thermostat valves do not support the setting of modes. 
Therefore, I'm unable to define the thermostats in the hass/devices.js as a thermostat.
Since, the current way the code is setup, it isn't possible to add thermostats without modes.
This pull request is a suggestion which would make it possible to add thermostat devices without modes to home assistant.
Adding HVAC (thermostat) devices to homeassistant without modes is possible: https://www.home-assistant.io/integrations/climate.mqtt/ . (The documentation of home assistant defines the mode values as optional.)
Currently, I've tested these changes with my thermostat devices and they now show up in home assistant as thermostats (HVAC's).
Note1: For this device to be recognized by …
=> Make it possible for homeassistant to recognize thermostat valves without modes

lib/Gateway.js
This should fix issue reported in #99 and #178. Might not be perfect, but definitely better than having Z2M crash without any good hint about the reason.
=> Fixed crash when components are set to {}

src/components/ControlPanel.vue
"charaters" is a spelling error; it may still need commas -- Oxford, of course!  Additionally, slight inconsistency in uppercase/lowercase, and pluralism agreement.
There remains an outstanding oddity on multi instance association description.
Additionally, line 721 should be "nodes' names and locations", but since " ' " is the delimiter on the text string, I can't use it as an apostrophe.  Maybe "node names and locations" remains valid english.
=> Spelling and consistency (no change in behavior)

lib/ZwaveClient.js
This patch allows using the api topic to send raw Z-Wave packets. This is extremely useful for devices like the EUROtronic SPIRITZ thermostat, which requires raw messages to use an external temperature source.
Note: This api is only available in very recent versions of OpenZWave.
=> Enable sending raw zwave data

build/webpack.dev.conf.js, lib/Gateway.js
If you use a customDevices.json this will now be re-read on every node discovery instead of being read once when you start the server.
This makes it easier to build out z-wave networks without being forced into network scans due to restarts
Dynamic parsing of customDevices.js is not suported (would either require clearing require cache hack or evaling) but it is still read at startup to continue supporting it.
It also adds `disableHostCheck` for webpack dev-server to enable reaching it over something else than localhost when you set `HOST=0.0.0.0`
=> Support dynamic reads of customDevices.json

hass/configurations.js, lib/Gateway.js
Not all alarm command class indeces below 256 are burglar according to https://github.com/OpenZWave/open-zwave/blob/4478eea26b0e1a29184df0515a8034757258ff88/cpp/src/ValueIDIndexesDefines.def#L1068
This PR sets sensor_home_security to index 7 and sensor_access_control to index 6.
Cheers,
=> set sensor_home_security to index 7, sensor_access_control to 6

hass/devices.js, lib/Constants.js, lib/Gateway.js
This refactors how we determine multilevel sensor types to be similar to how we do alarm sensors. It includes the names for the object ids.
@robertsLando there are some cases where the object id has the same name as the sensor type, so I kept it blank to avoid names like `direction_direction`. Let me know what you think.
Also, some sensors look like they belong to other types, but I didn't want to move them around just yet. For example, sensor 57 is under *sensor_water*, but it's a water pressure sensor, and maybe it should be under *sensor_pressure* instead..
Another thing to consider is in the future we may want to populate not just object ids but also units of measurement based on the constants.
It would be really great if instead of redefining things in the Constants.js if we could …
=> refactor: sensor multilevel constants

lib/Constants.js
Electricity kwh meter got classified and named as a water meter instead as an electricity meter as it is supposed to be. sensor_water_kwh_meter instead of sensor_electricity_kwh_meter.
=> Fix electricity meter named as water meter

src/components/ControlPanel.vue
Adding one more node command - removeFailedNode 
- this command can be used after a node is Dead or "Has node failed" been executed against node.
- This command can delete/remove permanently a node from the controller
=> Add "remove failed node" command

hass/configurations.js
I think this fixes #68 , @robertsLando, but I'm not sure if I should change this here for all rgb_dimmers, or if we should break out the two specific models mentioned in the issue in `hass/devices.js`
- Zipato Bulb 2
- Aeon Labs ZW098
Thoughts?
=> make rgb_dimmer have state in caps and use RGB

README.md
Correct spelling of changelog.
=> Correct spelling of chengelog/changelog

lib/Gateway.js
With the current behavior for thermostat/climate devices values received from HASS for fan modes are translated using the mode_map. However, the mode_map only maps modes for the hvac mode, not the fan mode.
This change makes it so the fan mode command class will map its values against the fan_mode_map instead of the mode_map.
=> use fan_mode_map instead of mode_map for thermostat_fan_mode command class

lib/Gateway.js
This simplifies the mode map template by eliminating the conditional and just using jinja's default filter instead. I was able to test it with string values but not with integer values.
=> simplify the mapped values template by using jinja's default filter

lib/Gateway.js
Have a more precise reading as a default seems to do no harm and will give better reading for those who have thermostats that report temperature with a more granular precision than 1.0 degree.
Users can still override the precision by setting it in the customDevices.json or the devices.js. If no precision is set then the default is used.
=> default precision to 0.1 on hass discovery climate devices

hass/devices.js
Added support for discovery of 2 cover devices for home assistant.
- Fibaro FGS222
- Qubino flush shutter
All functions of the cover work except for the stop button.
It isn't possible to make it work with the MQTT cover implementation in hass.
For stopping a cover you need to send false to 38/1/2. This isn't possible with the MQTT cover implementation in hass. That implementation uses only 1 command topic where you can send a open, close and stop command to.
Users who need the stop command can better use the template cover.
Example:
```
sensor:
- platform: mqtt
name: "zonwering_woonkamer"
state_topic: "zwave2mqtt/8/38/1/0"
value_template: "{{ (value_json.value / 99 * 100) | round(0) }}"
cover:
- platform: template
covers:
zonwering_woonkamer:
friendly_name: "Zonwering woonkamer" …
```
=> Added discovery configuration for fibaro FGS222 and the Qubino flush shutter

hass/devices.js
This should add support fro the Hortmann HRT4-ZW device. 
I've tested this briefly after running it with the customDevices for a while. I copied the values from there.
=> Add HRT4-ZW device from Hortmann.

README.md, lib/ZwaveClient.js, src/components/Settings.vue
As discussed in and closes #359 [[feat] expose the zwave client](/OpenZWave/Zwave2Mqtt/issues/359)
First time i've touched anything to do with vue, so no idea if this is the right/best way to do it?
=> allow a zwave plugin to be defined exposing the zwave client to external js

hass/devices.js
Created by copying CT32 configuration. Tested and it seems to work fine in home assistant
=> add CT101 thermostat configuration

lib/Gateway.js
https://github.com/OpenZWave/Zwave2Mqtt/issues/357
home assistant uses ```°C``` and ```°F``` for temperature units instead of plain ```C``` and ```F```.
Thus we need to either have zwave2mqtt convert it as part of the hass device JSON template, or handle it on home assistant side to override unit of measurement for every temperature sensor device.
This PR handles it on zwave2mqtt side.
=> map temperature units to hass values

src/components/ControlPanel.vue
The labels overlapped the new name/location fields. Changed the xs sizing to 4 and 8 for the label and input respectively. Also made the ID full width.
=> Bug #424 Fixing display issue on mobile

hass/devices.js
This change depends on the following patch to OpenZWave: https://github.com/OpenZWave/open-zwave/pull/2289
=> [devices] Add Intermatic PE653 MultiWave Receiver

README.md, lib/MqttClient.js
Fixes #638
BREAKING CHANGE: Default Hass Birth/Will topic is changed from `hass/status` to `homeassistant/status` to reflect defaults of Hass 0.113
=> fix: change default hass birth/will topic

lib/Gateway.js, test/lib/Gateway.test.js
Although my specific use case is still broken because of the behavior of docker single file mounts, this appears to fix #670 
```
$ docker run --name=z2m --entrypoint=/bin/sh -it robertslando/zwave2mqtt:latest
$ echo '{}' > store/customDevices.json
$ node bin/ww
…
z2m:Gateway Loaded 0 custom Hass devices configurations +0ms
…
```
Then, in a new window:
```
$ docker exec -it z2m /bin/sh
$ apk add vim
$ vim store/customDevices.json
…add something / change the file; `:wq`
```
Back in the first window, I see:
```
z2m:Gateway Error while reading /usr/src/app/store/customDevices.json ENOENT: no such file or directory, open '/usr/src/app/store/customDevices.json' +20s
```
```
z2m:Gateway re-setting watch on /usr/src/app/store/customDevices.json +14s
z2m:Gateway Error while reading …
```
=> fix: improved watch logic of customDevices

lib/Gateway.js
@chilicheech Check out this please
=> fix: set temperature_unit in climate discovery #731

README.md, lib/Gateway.js, package-lock.json, package.json, src/components/dialogs/DialogGatewayValue.vue
This will allow users to specify a custom parse/recieve js function in gateway values table :)
=> feat: parse value functions #739

hass/devices.js
Create a climate device for Eurotronic StellaZ in home-assistant.
StellaZ functions the same as SpiritZ.
I tested:
* temperature set point
* current temperature
* thermostat mode (Off, Heat, Cool)
The mode mapping is a bit weird since for Stella and Spirit it would normally be 'Heat' and 'Eco' rather than 'Heat' and 'Cool'. But perhaps there are reasons why Spirit was written that way.
=> feat(hass): Eurotronic Stella Z thermostat

.github/workflows/close-stale.yml
attempt to tidy up the backlog of issues+prs and make sure they're still relevant.
hopefully the text reads friendly enough, suggest we try at 30 and see if we need to increase the days if it's more annoying than useful
adding `no-stale` label will prevent it applying to any of the longer term features/prs etc
=> close stale issues+prs

hass/devices.js
I have several CT100 zwave thermostats, the existing 2GIG template works fine, just adding a new device id line for this particular thermostat.
=> adding CT100 using 2GIG template

.github/workflows/dockerbuild.yml, hass/configurations.js, lib/Constants.js, lib/Gateway.js, lib/ZwaveClient.js, test/lib/Constants.test.js
The main goal of this PR is to fix #329 
There are two main changes:
1. in the Zwave client, adding to the zwave nodes the basic, generic and specific device class as provided by the openzwave stack. I also added the constants for all the generic/specific classes.
2. in the Gateway, adapting the hass discovery logic to use the cover_position entity instead of the light_dimmer
I tested it with the Aeotec NanoShutter: https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw141.xml
This **only** solves discovery of the "cover position".
Looking at my Aeotec device I see many other controls that could be discovered in a more "specific" way. Unfortunately I don't know if this kind of device is more or less standardized or if any vendor comes up with different sets of commands and …
=> feat: improve HASS discovery of cover devices

README.md
It's not needed to install libudev-dev in order to compile open-zwave
=> libudev.h shouldn't be required with ozw 1.6

README.md, lib/ZwaveClient.js
Allows more zwave settings to be declared via environment variables
- `OZW_SAVE_CONFIG`
- `OZW_POLL_INTERVAL`
- `OZW_AUTO_UPDATE_CONFIG`
- `OZW_CONFIG_PATH`
- `OZW_ASSUME_AWAKE`
=> fix: implement more environment variables for configuration

src/components/ControlPanel.vue
=> fix: allow `/` char in name and location #790

lib/ZwaveClient.js
This updates the last active timestamp not only on status changes but on every value change a node reports.
I introduced a triggerStatusUpdate variable to prevent multiple updates within valueChanged().
Has been tested successfully on my local setup.
closes #490
=> feat: Update last active on value changes

src/components/ControlPanel.vue, src/components/nodes-table/filter-options.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.css, src/components/nodes-table/nodes-table.js, src/modules/NodeCollection.js, src/modules/NodeCollection.test.js
This PR is a merged and improved version of #582 and #800 and adds the possibility to filter nodes by their column values.
Filtering can done by the following ways:
* Search for a sub-string
* Select from a list of values
* Set min/max number values
* Set min/max date values
**Screenshots:**
Icons have been added to activate the filter options and to indicate a filtered column:
Example of a substring and list selection filter:
Example of min/max number value filter:
Example of min/max date value filter:
=> feat: Add node table filter
