lib/Gateway.js
Sorry! I mixed these two up and need to send a quick patch.
=> [fix] Mixed up alarm type and level

lib/debug.js
=> [feat] allow usage of DEBUG environment variable

hass/devices.js
Add proper value for Temperature step on Eurotronic Spirit TRV
=> Fix temp_step for Eurotronic Spirit TRVs

hass/devices.js
1. Added Danfoss and Danfoss Based TRVs (Devolo and Popp)
2. Added more Eurotronics Spirit device IDs
=> Add more TRVs

lib/Constants.js
=> use a map to get command class names to reduce code complexity

hass/configurations.js
=> fix light on/off state value template to use lowercase values

lib/Gateway.js
=> render the action_topic and reformat the code a little

README.md, hass/devices.js
add 2gig ct32 thermostat, fix lint issues, and update readme thermostat example
=> add 2gig ct32 thermostat

hass/devices.js
Added Graber/Bali/Spring Fashion Covers to devices.js
=> Update devices.js for new cover type

README.md, lib/ZwaveClient.js, src/components/Settings.vue
As discussed in and closes #358 [[feat] arbitrary zwave config](/OpenZWave/Zwave2Mqtt/issues/358)
=> feat: arbitrary zwave config

hass/devices.js, lib/ZwaveClient.js
=> reduce code duplication by putting the common 2gig thermostat definition in a variable/constant

wallaby.js
see https://wallabyjs.com/ for detail
=> add wallaby.js support for rapid testing

.github/workflows/ci.yml
brings builds from ~4mins down to <1m for routine stuff, can be tweaked to be a bit more refined if needed
=> cache ci slow steps

lib/debug.js
=> point debug output to stdout not stderror

src/components/Mesh.vue
=> fix: mesh link color with dark mode #444

.github/workflows/dockerbuild.yml
I have found an interesting github action for events dispatch. Check this out. Zwave2Mqtt-docker repo has been already updated to support this, once this is merget it should trigger a new build there
=> docker build dispatch event

src/components/ControlPanel.vue
=> fix: node select background color #452

src/components/ControlPanel.vue
=> fix: allow empty node name/location #463

.github/workflows/ci.yml
=> apt-get update before installing deps

lib/Gateway.js, lib/MqttClient.js, src/components/ControlPanel.vue
=> feat: subscribe using wildecards

hass/configurations.js, lib/Gateway.js
=> feat: hass barrier_operator class support #445

src/components/ControlPanel.vue, src/components/ValueId.vue
=> fix: Use readonly fields intead of disabled #480

.github/workflows/dockerbuild.yml
fix what the expected value of `git.ref` should be
=> fix docker build

docs/subpath.md, test/lib/renderIndex.test.js
=> Fix a mismatch between sample code and text

lib/ZwaveClient.js
=> fix: set node status to initializing when firstly added

lib/ZwaveClient.js, src/App.vue, src/components/ControlPanel.vue
=> feat: show associations of multi-instance devices #637

src/components/ControlPanel.vue
=> fix: removeAssociation with multi instance devices

src/App.vue, views/index.ejs
=> feat: change meta theme-color based on theme #669

.github/dependabot.yml
note docker is set to automerge
=> dependabot update github actions and docker

src/components/ControlPanel.vue
=> fix: Rows per page not set correctly

README.md, hass/devices.js
Tested set point, mode and current temperature.
Not sure if you want to add the device id to the sample code. It wasn't clear to me, so I thought i'd suggest it.
=> Added Home Assistant support for HeatIt TRM3
